language: groovy

jdk:
  - openjdk7
  - oraclejdk7

env:
- GRAILS_VERSION=3.2.4


before_install:
- rm -rf ~/.gvm
- curl -s get.gvmtool.net > ~/install_gvm.sh
- chmod 775 ~/install_gvm.sh
- ~/install_gvm.sh
- echo "gvm_auto_answer=true" > ~/.gvm/etc/config
- source ~/.gvm/bin/gvm-init.sh
- gvm install grails $GRAILS_VERSION || true

branches:
  only:
    - master
    - more-testing

script: grails clean
     && grails upgrade --non-interactive
     && grails test-app --non-interactive


notifications:
  email: false
  slack: frctristarcollab:jsFS3EN9AbPL31QLUlJL4MTH