language: groovy

jdk:
  - openjdk7
  - oraclejdk7

script:
  - sudo ./grailsw refresh-dependencies
  - sudo ./grailsw test-app -coverage -xml
after_success:
  - sudo ./grailsw coveralls


notifications:
  email: false
  slack: frctristarcollab:jsFS3EN9AbPL31QLUlJL4MTH